import Image from "next/image";
import { BottomLeft, BottomRight, TopLeft, TopRight } from "../assets/icons";

const WhyBitStacker = () => {
  return (
    <div className="relative w-full p-10 my-60" id="WhatsBitstacker">
      <div className="absolute left-0 top-0">
        <TopLeft />
      </div>
      <div className="absolute right-0 top-0">
        <TopRight />
      </div>

      <div className="text-center">
        <h1 className="font-medium text-3xl text-[#F3F3F3]">
          What is Bitstacker?
        </h1>
        <p className="text-[#BDBDBD] text-xl font-light mt-5 leading-[30px]">
          By utilizing the best features of Ethereum Smart Contracts we have
          created an innovative concept in Cloud Mining services called
          BitStacker. It is a collection of NFTs split into 2 tiers – & These
          tiers grant the holder a perpetual ownership of fractionalized
          hashpower generated by physical Bitcoin mining machines with up to
          40,000 Th/s of distributable hashrate. Proceeds from the sales will be
          directly used to purchase & setup the miners as well as cover all the
          associated operating costs. These miners will be professionally
          installed in various commercially viable facilities and operated
          24/7/365 by an experienced team of technicians. Once the mining farm
          is up and running, our team of specialized technicians will manage &
          maintain the miners at optimal efficiency levels, giving you the
          highest returns possible without sacrificing its functionality &
          lifespan. This will ensure the holders receive a guaranteed monthly
          reward in Bitcoin.
        </p>
      </div>
      <div className="flex justify-center relative">
        <div className="absolute top-8">
          <Image
            alt="line"
            width={700}
            height={10}
            src={"/assets/icons/line.svg"}
          />
        </div>
        <div className="absolute -top-[31px]  left-1/2 -translate-x-1/2">
          <Image
            alt="star"
            width={170}
            height={150}
            src={"/assets/icons/star.svg"}
          />
        </div>
      </div>
      <div className="absolute left-0 bottom-0">
        <BottomLeft />
      </div>
      <div className="absolute right-0 bottom-0">
        <BottomRight />
      </div>
    </div>
  );
};

export default WhyBitStacker;
